Imdb/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from movie.views import HomeView

urlpatterns = [

    path('' , HomeView.as_view()),
    path('admin/', admin.site.urls),
    path('movies/', include('movie.urls', namespace='movies'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path
from .views import MovieList , MovieDetail , MovieCategory , MovieLanguage , MovieSearch , MovieYear


app_name='movie'

urlpatterns = [
    path('', MovieList.as_view() , name='movie_list'),
    path('category/<str:category>', MovieCategory.as_view() , name='movie_category'),
    path('language/<str:lang>', MovieLanguage.as_view() , name='movie_language'),
    path('search/', MovieSearch.as_view() , name='movie_search'),
    path('<slug:slug>', MovieDetail.as_view() , name='movie_detail'),
    path('year/<int:year>', MovieYear.as_view() , name='movie_year'),
]

movie/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
# Create your models here.

CATEGORY_CHOICES = (
    ('action','ACTION'),
    ('drama','DRAMA'),
    ('comedy','COMEDY'),
    ('romance','ROMANCE'),
)

LANGUAGE_CHOICES = (
    ('english' , 'ENGLISH'),
    ('german' , 'GERMAN'),
)

STATUS_CHOICES = (
    ('RA' , 'RECRNTLY ADDED'),
    ('MW' , 'MOST WATCHED'),
    ('TR' , 'TOP RATED'),
)

class Movie(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    image = models.ImageField(upload_to='movies')
    banner = models.ImageField(upload_to='movies_banner')
    category = models.CharField(choices=CATEGORY_CHOICES , max_length=10)
    language = models.CharField(choices=LANGUAGE_CHOICES , max_length=10)
    status = models.CharField(choices=STATUS_CHOICES , max_length=2)
    cast = models.CharField(max_length=100)
    year_of_production = models.DateField()
    views_count = models.IntegerField(default=0)
    movie_trailer = models.URLField()

    created = models.DateTimeField(default=timezone.now)

    slug = models.SlugField(blank=True, null=True)

    def save(self , *args , **kwargs):
        if not self.slug :
            self.slug = slugify(self.title)
        super(Movie , self).save( *args , **kwargs)

    def __str__(self):
        return self.title


 	# tags
 	# - download links
 	# - watch links

LINK_CHOICES = (
    ('D' , 'DOWNLOAD LINK'),
    ('W' , 'WATCH LINK'),
)


class MovieLinks(models.Model):
    movie = models.ForeignKey(Movie, related_name='movie_watch_link', on_delete=models.CASCADE)
    type = models.CharField(choices=LINK_CHOICES , max_length=1)
    link = models.URLField()

    def __str__(self):
        return str(self.movie)

movie/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView , DetailView
from django.views.generic.dates import YearArchiveView
from .models import Movie , MovieLinks





class HomeView(ListView):
    model = Movie
    template_name = 'movie/home.html'

    def get_context_data(self , **kwargs):
        context = super(HomeView , self).get_context_data(**kwargs)
        context['top_rated'] = Movie.objects.filter(status='TR')
        context['most_watched'] = Movie.objects.filter(status='MW')
        context['recently_added'] = Movie.objects.filter(status='RA') 
        return context


class MovieList(ListView):
    model = Movie
    paginate_by = 2


class MovieDetail(DetailView):
    model = Movie

    def get_object(self):
        object = super(MovieDetail , self).get_object()
        object.views_count += 1
        object.save()
        return object

    def get_context_data(self , **kwargs):
        context = super(MovieDetail , self).get_context_data(**kwargs)
        context['links'] = MovieLinks.objects.filter(movie=self.get_object())
        context['related_movies'] = Movie.objects.filter(category=self.get_object().category)#.order_by['created'][0:6]
        return context


class MovieCategory(ListView):
    model = Movie
    paginate_by = 2

    def get_queryset(self):
        self.category = self.kwargs['category']
        return Movie.objects.filter(category=self.category)

    def get_context_data(self , **kwargs):
        context = super(MovieCategory , self).get_context_data(**kwargs)
        context['movie_category'] = self.category
        return context



class MovieLanguage(ListView):
    model = Movie
    paginate_by = 2

    def get_queryset(self):
        self.language = self.kwargs['lang']
        return Movie.objects.filter(language=self.language)

    def get_context_data(self , **kwargs):
        context = super(MovieLanguage , self).get_context_data(**kwargs)
        context['movie_language'] = self.language
        return context




class MovieSearch(ListView):
    model = Movie
    paginate_by = 2

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query:
            object_list = self.model.objects.filter(title__icontains=query)
        
        else:
            object_list = self.model.objects.none()

        return object_list

class MovieYear(YearArchiveView):
    queryset = Movie.objects.all()
    date_field = 'year_of_production'
    make_object_list = True
    allow_future = True

    print(queryset)
        

movie/templates/movie/home.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  

		<main class="content">
			<section class="panel">
				<h2>Recently Added</h2>
				<div class="recentslider">
					<div class="swiper-container">
						<div class="swiper-wrapper">
                            {% for movie in recently_added %} 
							    <div class="swiper-slide"><a href="single.html"><img src="{{movie.image.url}}"><h3 class="hometitle">{{movie.title}}</h3></a></div>
                            {% endfor %}
							<div class="swiper-slide"><a href="mostwatched.html"><img src="{% static 'img/others.png' %}"></a></div>
						</div>
						<div class="nextdirection recent-next"><img src="{% static 'img/right-arrow.svg' %}"> </div>
						<div class="leftdirection recent-prev"><img src="{% static 'img/left-arrow.svg' %}"> </div>
					</div>
				</div>
			</section>

			<section class="panel">
				<h2>Most Watched</h2>
				<div class="mostslider">
					<div class="swiper-container">
						<div class="swiper-wrapper">
                            {% for movie in most_watched %} 
							    <div class="swiper-slide"><a href="single.html"><img src="{{movie.image.url}}"><h3 class="hometitle">{{movie.title}}</h3></a></div>
                            {% endfor %}
							<div class="swiper-slide"><a href="mostwatched.html"><img src="{% static 'img/others.png' %}"></a></div>
						</div>
						<div class="nextdirection most-next"><img src="{% static 'img/right-arrow.svg' %}"> </div>
						<div class="leftdirection most-prev"><img src="{% static 'img/left-arrow.svg' %}"> </div>
						<!-- Add Pagination -->
					</div>
				</div>
			</section>

			<section class="panel">
				<h2>Top Rated</h2>
				<div class="topslider">
					<div class="swiper-container">
						<div class="swiper-wrapper">
                            
                            {% for movie in top_rated %}  
							    <div class="swiper-slide"><a href="single.html"><img src="{{movie.image.url}}"><h3 class="hometitle">{{movie.title}}</h3></a></div>
                            {% endfor %}
							<div class="swiper-slide"><a href="mostwatched.html"><img src="{% static 'img/others.png' %}"></a></div>
						</div>
						<div class="nextdirection top-next"><img src="{% static 'img/right-arrow.svg' %}"> </div>
						<div class="leftdirection top-prev"><img src="{% static 'img/left-arrow.svg' %}"> </div>
						<!-- Add Pagination -->
					</div>
				</div>
			</section>

			
		</main>

        {% endblock body %}

movie/templates/movie/movie_archive_year.html
{% extends 'base.html' %}
{% block body %}
		<main class="content">
			<section class="centered">
                {% if movie_category %}
                    <h3>{{movie_category|title}} Movies</h3>
                {% endif %}
               
                {% if movie_language %}
                    <h3>{{movie_language|title}} Movies</h3>
                {% endif %}

				<div class="movies">
                    {% for movie in object_list %}
                        <div class="mov">
                            <a href="">
                                <img src="{{movie.image.url}}">
                                <h2 class="movietitle">{{movie.title}}</h2>
                            </a>
                        </div>
                    {% empty %}
                        <h3>There Are No Movies In This Category</h3>
                    {% endfor %}

                </div>
                {% if is_paginated %}
                    <nav class="pagination">
                        <ul>
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                            {% else %}
                                <li class="disabled"></li>
                            {% endif %}
                            
                            {% for pages in page_obj.paginator.page_range %}
                              {% if page_obj.number == pages %}
                                <li><a href="#">{{pages}}</a></li>
                              {% else %}
                                <li><a href="?page={{pages}}">{{pages}}</a></li>
                              {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
                            {% else %}
                                <li class="disabled"></li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
			</section>

		</main>
{% endblock body %}

movie/templates/movie/movie_detail.html
{% extends 'base.html' %}
{% block body %}
  

		<main class="content">
			<div class="single">

				<section class="trailer">
					<h3>Trailer</h3>
					<div class="trailer_frame">
						<iframe width="560" height="315" src="{{object.movie_trailer}}" frameborder="0" allowfullscreen></iframe>
					</div>
				</section>

				<section class="movie">
					<img src="{{object.image.url}}">
					<ul>
						<li>{{object}}</li>
						<li>{{object.decription}}</li>
						<li><a href="genre.html">Adventure</a>, <a href="genre.html">Drama</a>, <a href="genre.html">Romance</a></li>
						<li><a href="">{{object.cast}}</a></li>
						<li>{{object.views_count}} Views</li>
					</ul>
				</section>
				<section class="links">
					<h3>Links</h3>
					<ul class="dlinks">
						<li><a>Download</a></li>
						
						{% for link in links  %}
							{% if link.type == 'D' %}
							<li><a href="{{link.link}}">link{{forloop.counter}}</a></li>
							{% endif %}
						{% endfor %}
							
						
					</ul>
					<ul class="wlinks">
						<li><a>Watch</a></li>
						{% for link in links  %}
							{% if link.type == 'W' %}
							<li><a href="{{link.link}}">link{{forloop.counter}}</a></li>
							{% endif %}
						{% endfor %}

					</ul>
				</section>

				<section class="related">
					<h3>Related movies</h3>
					
					{% for movie in related_movies %}
						<div class="relatemovie">
							<a href="{% url 'movies:movie_detail' movie.slug %}"><img src="{{movie.image.url}}"></a>
							<a href="{% url 'movies:movie_detail' movie.slug %}"><span class="relatedname">{{movie.title}}</span></a>
						</div>
					{% endfor %}

				</section>


			</div>
		</main>

{% endblock body %}

movie/templates/movie/movie_list.html
{% extends 'base.html' %}
{% block body %}
		<main class="content">
			<section class="centered">
                {% if movie_category %}
                    <h3>{{movie_category|title}} Movies</h3>
                {% endif %}
               
                {% if movie_language %}
                    <h3>{{movie_language|title}} Movies</h3>
                {% endif %}

				<div class="movies">
                    {% for movie in object_list %}
                        <div class="mov">
                            <a href="{% url 'movies:movie_detail' movie.slug %}">
                                <img src="{{movie.image.url}}">
                                <h2 class="movietitle">{{movie.title}}</h2>
                            </a>
                        </div>
                    {% empty %}
                        <h3>There Are No Movies In This Category</h3>
                    {% endfor %}

                </div>
                {% if is_paginated %}
                    <nav class="pagination">
                        <ul>
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                            {% else %}
                                <li class="disabled"></li>
                            {% endif %}
                            
                            {% for pages in page_obj.paginator.page_range %}
                              {% if page_obj.number == pages %}
                                <li><a href="#">{{pages}}</a></li>
                              {% else %}
                                <li><a href="?page={{pages}}">{{pages}}</a></li>
                              {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
                            {% else %}
                                <li class="disabled"></li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
			</section>

		</main>
{% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Movies</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

	<!-- Link Swiper's CSS -->
	<link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">

	<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
	<script src="{% static 'js/script.js' %}"></script>


	<!-- Demo styles -->
	<style>



	</style>
</head>
<body>
	<div class="wrapper">

		<header class="header">
			<figure class="logo"><a href="/"><img src="{% static 'img/logo.png' %}" alt="Logo"></figure></a>
			<nav class="menu">
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a>Genres</a>
						<ul>
							<li><a href="{% url 'movies:movie_category' 'action' %}">Action</a></li>
							<li><a href="{% url 'movies:movie_category' 'comedy' %}">Comedy</a></li>
							<li><a href="{% url 'movies:movie_category' 'drama' %}">Drama</a></li>
							<li><a href="{% url 'movies:movie_category' 'romance' %}">Romance</a></li>
						</ul>
					</li>
					<li><a>Year</a>
						<ul>
							<li><a href="{% url 'movies:movie_year' year=2019 %}">2019</a></li>
							<li><a href="{% url 'movies:movie_year' year=2018 %}">2018</a></li>
							<li><a href="{% url 'movies:movie_year' year=2017 %}">2017</a></li>
							<li><a href="{% url 'movies:movie_year' year=2016 %}">2016</a></li>
						</ul>
					</li>
					<li><a>Language</a>
						<ul>
							<li><a href="{% url 'movies:movie_language' 'english' %}">English</a></li>
							<li><a href="{% url 'movies:movie_language' 'german' %}">German</a></li>
						</ul>
					</li>
					<li class="mobsearch">
						<form class="mobform" method="GET">
							<input type="text" name="query" value="{{ request.GET.q}}" class="mobsearchfield" placeholder="Search...">
							<input type="submit" value="" class="mobsearchsubmit">
						</form>
					</li>
				</ul>
			</nav>
			<form class="search" method="GET" action="{% url 'movies:movie_search' %}">
				<input type="text" name="query" value="{{ request.GET.q}}" class="searchfield" placeholder="Search...">
				<input type="submit" value="" class="searchsubmit">
			</form>

			<div class="toggle"><img src="img/menu.svg"></div>
		</header>
		<!-- Swiper -->
		<div class="homeslider">
			<div class="swiper-container">

				<div class="swiper-wrapper">
					
	
					
					{% for movie in slider_movie %}
						
						<div class="swiper-slide">
							{% if movie.banner %}
								<img src="{{movie.banner.url}}">
							{% endif %}
							
							<div class="caption">
								<div class="captioninside">
									<h3>{{movie.title}}</h3>
									<p>{{movie.description}}</p>
									<a href="{% url 'movies:movie_detail' movie.slug %}" class="playbutton">Play</a>
								</div>
							</div>
						</div>
				
					{% endfor %}
				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination"></div>
			</div>
		</div>

		{% block body %}
		  
		{% endblock body %}

		<footer class="footer">
			<div class="copyright"><p>Copyright &copy 2017 www.focusoncode.com</p></div>
			<div class="footermenu">
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="contact.html">Contact</a></li>
					<li><a href="terms.html">Terms and conditions</a></li>
				</ul>
			</div>
			<div class="tags">
				<ul>
					<li>Watch Free Movies Trailers</li>
					<li>Movie Trailers</li>
					<li>English Subtitled Movies Trailers</li>
					<li>Latest Movies Trailers</li>
					<li>New Movies Trailers</li>

				</ul>
			</div>

		</footer>

		<!-- Swiper JS -->
		<script src="{% static 'js/swiper.min.js' %}"></script>

		<!-- Initialize Swiper -->
		<script>
			$(document).ready(function(){


				var swiper = new Swiper('.homeslider > .swiper-container', {
					pagination: '.swiper-pagination',
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					effect:'fade',
					breakpoints: {
						320: {
							height:200
						},

						480: {
							height:300
						},

						768: {
							height:400
						},
						1024: {
							height:500
						}
					}
				});

				var recentswiper = new Swiper('.recentslider > .swiper-container', {
					nextButton: '.recent-next',
					prevButton: '.recent-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

				var mostswiper = new Swiper('.mostslider > .swiper-container', {
					nextButton: '.most-next',
					prevButton: '.most-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

				var topswiper = new Swiper('.topslider > .swiper-container', {
					nextButton: '.top-next',
					prevButton: '.top-prev',
					slidesPerView: 8,
					paginationClickable: true,
					preventClicks:false,
					preventClicksPropagation:false,
					spaceBetween: 10,
					breakpoints: {
						320: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						480: {
							slidesPerView: 3,
							spaceBetween: 5
						},

						768: {
							slidesPerView: 5,
							spaceBetween: 5
						},
						1024: {
							slidesPerView: 6,
							spaceBetween: 10
						}
					}
				});

			});

			
		</script>


	</div>
</body>
</html>